#include <spine/Extension.h>

namespace spine {
SpineExtension *getDefaultExtension() {
    return new DefaultSpineExtension();
}
}

#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Animation.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/AnimationState.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/AnimationStateData.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Atlas.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/AtlasAttachmentLoader.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Attachment.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/AttachmentLoader.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/AttachmentTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Bone.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/BoneData.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/BoundingBoxAttachment.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/ClippingAttachment.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/ColorTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/ConstraintData.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/CurveTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/DeformTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/DrawOrderTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Event.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/EventData.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/EventTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Extension.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/IkConstraint.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/IkConstraintData.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/IkConstraintTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Json.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/LinkedMesh.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/MathUtil.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/MeshAttachment.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/PathAttachment.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/PathConstraint.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/PathConstraintData.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/PathConstraintMixTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/PathConstraintPositionTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/PathConstraintSpacingTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/PointAttachment.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/RTTI.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/RegionAttachment.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/RotateTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/ScaleTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/ShearTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Skeleton.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/SkeletonBinary.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/SkeletonBounds.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/SkeletonClipping.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/SkeletonData.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/SkeletonJson.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Skin.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Slot.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/SlotData.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/SpineObject.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/TextureLoader.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Timeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/TransformConstraint.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/TransformConstraintData.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/TransformConstraintTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/TranslateTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Triangulator.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/TwoColorTimeline.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/Updatable.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/VertexAttachment.cpp"
#include "../../vendor/spine-cpp-3.8.95/spine-cpp/src/spine/VertexEffect.cpp"
